name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Reemplaza 'main' con el nombre de tu rama principal
      - develop
  pull_request:
    branches:
      - main  # Reemplaza 'main' con el nombre de tu rama principal
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Selecciona la versión de Node.js que necesites

      - name: Install Dependencies
        run: npm install  # O yarn install si prefieres Yarn

      - name: Build Next.js App
        run: npm run build
